import turtle
t = turtle.Turtle()
t.hideturtle()
t.penup()
t.goto(100, 200)
t.showturtle()
t.pendown()
t.right(90)
t.forward(400)
t.hideturtle()
t.penup()
t.goto(-100, 200)
t.showturtle()
t.pendown()
t.forward(400)
t.hideturtle()
t.penup()
t.goto(-250, 100)
t.showturtle()
t.pendown()
t.left(90)
t.forward(500)
t.hideturtle()
t.penup()
t.goto(-250, -100)
t.showturtle()
t.pendown()
t.forward(500)
while True:
    firstPlayer = 1
    while firstPlayer < 5:
        count = firstPlayer + 1
        print("Which box you want to select")
        choice = int(input())
        if choice == 1:
            t.hideturtle()
            t.penup()
            t.goto(-215, 150)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 2:
            t.hideturtle()
            t.penup()
            t.goto(-10, 150)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 3:
            t.hideturtle()
            t.penup()
            t.goto(200, 150)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 4:
            t.hideturtle()
            t.penup()
            t.goto(-215, -10)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 5:
            t.hideturtle()
            t.penup()
            t.goto(0, 0)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 6:
            t.hideturtle()
            t.penup()
            t.goto(200, -10)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 7:
            t.hideturtle()
            t.penup()
            t.goto(-215, -200)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 8:
            t.hideturtle()
            t.penup()
            t.goto(-10, -200)
            t.showturtle()
            t.pendown()
            t.circle(20)
        elif choice == 9:
            t.hideturtle()
            t.penup()
            t.goto(200, -200)
            t.showturtle()
            t.pendown()
            t.circle(20)
        else:
            print("Wrong Input")
            break
    secondPlayer = 1
    while secondPlayer < 4:
        secondPlayer = secondPlayer + 1
        print("Which box you want to select")
        choice = int(input())
        if choice == 1:
            t.hideturtle()
            t.penup()
            t.goto(-215, 150)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 2:
            t.hideturtle()
            t.penup()
            t.goto(-10, 150)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 3:
            t.hideturtle()
            t.penup()
            t.goto(200, 150)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 4:
            t.hideturtle()
            t.penup()
            t.goto(-215, -10)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 5:
            t.hideturtle()
            t.penup()
            t.goto(0, 0)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 6:
            t.hideturtle()
            t.penup()
            t.goto(200, -10)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 7:
            t.hideturtle()
            t.penup()
            t.goto(-215, -200)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 8:
            t.hideturtle()
            t.penup()
            t.goto(-10, -200)
            t.showturtle()
            t.pendown()
            t.forward(30)
        elif choice == 9:
            t.hideturtle()
            t.penup()
            t.goto(200, -200)
            t.showturtle()
            t.pendown()
            t.forward(30)
            break